# ZeroStick build in Azure DevOps Pipelines
# AzDO Pipeline documentation: https://aka.ms/yaml

stages:
  - stage: Build
    displayName: Build ZeroStick
    jobs:
      - job: make_dist
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - bash: make dist
          - publish: build/ZeroStick.zip
            artifact: ZeroStick.zip
