# ZeroStick build in Azure DevOps Pipelines
# AzDO Pipeline documentation: https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
        - azure-pipelines.yml
        - README.md

stages:
  - stage: Build
    displayName: Build ZeroStick
    jobs:
      - job: make_dist
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - bash: make dist
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
              Contents: build/ZeroStick.zip
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: GitHubRelease@0
            inputs:
              gitHubConnection: zerostick
              repositoryName: zerostick/zerostick
              action: create
              tagSource: manual
              tag: $(Build.BuildNumber)
              assets: $(Build.ArtifactStagingDirectory)/*.zip
