# ZeroStick build in Azure DevOps Pipelines
# AzDO Pipeline documentation: https://aka.ms/yaml

stages:
  - stage: Build
    displayName: Build ZeroStick
    jobs:
      - job: make_image
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - bash: make image
          - publish: build/pi-gen/deploy/*.img
            artifact: ZeroStick.img
                            